---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: us-east-1

  tasks:
    - name: Get shell script to startup
      set_fact:
        user_data_file: "{{ lookup('file', 'scripts/startup.sh') }}"

    - name: Create launch template
      ec2_launch_template:
        name: Mod5-lt
        image_id: "ami-0cff7528ff583bf9a"
        key_name: "peele"
        instance_type: t3.micro
        iam_instance_profile: image-gallery-server-role
        user_data: "{{  user_data_file | b64encode }}"
        network_interfaces:
          - device_index: 0
            associate_public_ip_address: yes
            groups:
              - "{{ postgresSGTag.group_id }}"
              - "{{ nginx_sg.group_id }}"
        tags:
          Name: mod5-servers
        state: present
      register: mod5lt