---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: us-east-1

  tasks:
    - name: Create target group
      elb_target_group:
        name: mod5-nlb-tg
        protocol: TCP
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        stickiness_type: source_ip
        stickiness_enabled: false
        state: present
      register: m5tg

    - name: Create network load balancer
      elb_network_lb:
        name: mod5-nlb
        subnet_mappings:
          - SubnetId: "{{ pubsub.subnet.id }}"
            AllocationId: eipalloc-00febdd53eb12f28a
        listeners:
          - Protocol: TCP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ m5tg.target_group_name }}"
          - Protocol: TLS
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ m5tg.target_group_name }}"
            Certificates:
              - CertificateArn: arn:aws:acm:us-east-1:813633464346:certificate/2969c9a5-e314-422c-ac18-f00dda974625
        state: present
      register: m5nlb
